### ISSUE TITLE
Fatal error: fftw3.h: No such file or directory

### ISSUE THREAD

**Issue by ytakemon** [fj86/PoissonBinomial#1]
Hello,

I've tried to install PoissonBinomial using `install.packages()`, `devtools::install_github()`, and also via source code in your release, but have run into the same error each time (see below). I am using a CentOS Linux 7 and this behaviour persists when I use both R v4.0.2 and v4.1.0. I'm not quite sure how to troubleshoot this. Is there something you'd recommend that I try?

```
* installing *source* package ‘PoissonBinomial’ ...
** package ‘PoissonBinomial’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/gsc/software/linux-x86_64-centos7/gcc-7.2.0/bin/g++ -std=gnu++14 -I"/gsc/software/linux-x86_64-centos7/R-4.1.0-tcltk/lib64/R/include" -DNDEBUG -I../inst/include -I/usr/local/include   -I'/home/ytakemon/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c PoissonBinomial.cpp -o PoissonBinomial.o
PoissonBinomial.cpp:4:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
make: *** [PoissonBinomial.o] Error 1
ERROR: compilation failed for package ‘PoissonBinomial’
* removing ‘/home/ytakemon/R/x86_64-pc-linux-gnu-library/4.1/PoissonBinomial’
```

**Comment by DISOhda** [comment]
Hello Yuka,

The error message says that the package could not be compiled locally, because the FFTW3 library is missing. On Linux systems, packages are always compiled locally, there are no pre-compiled packages like on Windows or macOS.

I have absolutely no experience with CentOS, but with various Ubuntu and Arch derivates. On these, I had to make sure that a (Linux system) package (not R package!) like “fftw3”, “libfftw3”, “fftw3-dev” or “libfftw3-dev” are installed. I’m sure there is something similar on CentOS (maybe this one helps: https://centos.pkgs.org/7/centos-x86_64/fftw-devel-3.3.3-8.el7.x86_64.rpm.html).

I hope I could help you.

Best regards,
Florian

Von: Yuka Takemon ***@***.***>
Gesendet: Dienstag, 11. Oktober 2022 23:51
An: DISOhda/PoissonBinomial ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [DISOhda/PoissonBinomial] Fatal error: fftw3.h: No such file or directory (Issue #1)


Hello,

I've tried to install PoissonBinomial using install.packages(), devtools::install_github(), and also via source code in your release, but have run into the same error each time (see below). I am using a CentOS Linux 7 and this behaviour persists when I use both R v4.0.2 and v4.1.0. I'm not quite sure how to troubleshoot this. Is there something you'd recommend that I try?

* installing *source* package ‘PoissonBinomial’ ...



** package ‘PoissonBinomial’ successfully unpacked and MD5 sums checked



** using staged installation



** libs



/gsc/software/linux-x86_64-centos7/gcc-7.2.0/bin/g++ -std=gnu++14 -I"/gsc/software/linux-x86_64-centos7/R-4.1.0-tcltk/lib64/R/include" -DNDEBUG -I../inst/include -I/usr/local/include   -I'/home/ytakemon/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c PoissonBinomial.cpp -o PoissonBinomial.o



PoissonBinomial.cpp:4:10: fatal error: fftw3.h: No such file or directory



 #include <fftw3.h>



          ^~~~~~~~~



compilation terminated.



make: *** [PoissonBinomial.o] Error 1



ERROR: compilation failed for package ‘PoissonBinomial’



* removing ‘/home/ytakemon/R/x86_64-pc-linux-gnu-library/4.1/PoissonBinomial’

**Comment by ytakemon** [comment]
Thanks for the suggestion, @DISOhda. I will try to get our IT team to install it to see if that will resolve the issue.
